// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLm2BrCbmSvPIdRDr-DH5-5sARKC0aejE',
    appId: '1:659177993431:web:fffef52761a29be2846c92',
    messagingSenderId: '659177993431',
    projectId: 'chat-app-cd9cc',
    authDomain: 'chat-app-cd9cc.firebaseapp.com',
    storageBucket: 'chat-app-cd9cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn6HE1UoJ41pJrPMDJxtFPq8xfft_Evto',
    appId: '1:659177993431:android:11fcc7ac5c6d5cbe846c92',
    messagingSenderId: '659177993431',
    projectId: 'chat-app-cd9cc',
    storageBucket: 'chat-app-cd9cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBYfOJzYaVVvQrf52g9hK3zuwqfqqXX-Q',
    appId: '1:659177993431:ios:4c2b0f040378776d846c92',
    messagingSenderId: '659177993431',
    projectId: 'chat-app-cd9cc',
    storageBucket: 'chat-app-cd9cc.appspot.com',
    iosClientId: '659177993431-j2f8v719u5f5qequdvbs9b1po3cnan87.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );
}
